networks:
  cadlab_net: {}
secrets:
  mysql_root_pass:
    external: true
    name: mysql_root_pass
services:
  cadlab:
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    environment:
      CADLAB_INCLUDE_GIT: "true"
    image: docker.cadlab.io/self-hosted/cadlab:1.21.7
    networks:
      cadlab_net: {}
    secrets:
    - source: mysql_root_pass
    volumes:
    - ./configs:/etc/cadlab:rw
    - certs:/etc/ssl/cadlab:rw
    - ./backups:/var/cadlab/backups:rw
    - git-backups:/var/git-backups:rw
    - git-configs:/var/git-configs:rw
    - ./logs/cadlab:/var/log/cadlab:rw
    - source:/var/www:rw
  git-server:
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    image: docker.cadlab.io/git-server:13.3.6-1.7
    networks:
      cadlab_net: {}
    volumes:
    - ./configs:/etc/cadlab:rw
    - git-configs:/etc/gitlab:rw
    - certs:/etc/ssl/cadlab:rw
    - git-logs:/var/log/gitlab:rw
    - git-data:/var/opt/gitlab:rw
    - git-backups:/var/opt/gitlab/backups:rw
  mail-server:
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    image: docker.cadlab.io/mail-server:1.0.8
    networks:
      cadlab_net: {}
    volumes:
    - ./configs:/etc/cadlab:rw
  mysql:
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    environment:
      MYSQL_DATABASE: cadlab
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
    image: docker.cadlab.io/self-hosted/mysql:1.0.21
    networks:
      cadlab_net: {}
    secrets:
    - source: mysql_root_pass
    volumes:
    - data:/var/lib/mysql:rw
    - ./logs/mysql:/var/log/mysql:delegated
  nginx:
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    environment:
      CADLAB_INCLUDE_GIT: "true"
    image: docker.cadlab.io/self-hosted/nginx:1.0.16
    networks:
      cadlab_net: {}
    ports:
    - mode: host
      protocol: tcp
      published: 22
      target: 22
    - mode: host
      protocol: tcp
      published: 80
      target: 80
    - mode: host
      protocol: tcp
      published: 443
      target: 443
    volumes:
    - ./certificates:/certificates:rw
    - ./configs:/etc/cadlab:rw
    - certs:/etc/ssl/cadlab:rw
    - acme:/root/.acme.sh:rw
    - ./logs/nginx:/var/log/nginx:delegated
    - source:/var/www:rw
version: '3.7'
volumes:
  acme: {}
  certs: {}
  data: {}
  git-backups: {}
  git-configs: {}
  git-data: {}
  git-logs: {}
  source: {}

