networks:
  cadlab_net: {}
secrets:
  mysql_root_pass:
    external: true
    name: mysql_root_pass
services:
  cadlab:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: docker.cadlab.io/cadlab-sh:1.18.18
    networks:
      cadlab_net: {}
    secrets:
    - source: mysql_root_pass
    volumes:
    - ./configs:/etc/cadlab:rw
    - certs:/etc/ssl/cadlab:rw
    - ./backups:/var/cadlab/backups:rw
    - ./logs/cadlab:/var/log:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - source:/var/www:rw
  mail-server:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: docker.cadlab.io/mail-server:1.0.2
    networks:
      cadlab_net: {}
    volumes:
    - ./configs:/etc/cadlab:rw
  mysql:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      MYSQL_DATABASE: cadlab
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
    image: docker.cadlab.io/mysql-sh:1.0.16
    networks:
      cadlab_net: {}
    secrets:
    - source: mysql_root_pass
    volumes:
    - data:/var/lib/mysql:rw
    - ./logs/mysql:/var/log/mysql:delegated
  nginx:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: docker.cadlab.io/nginx-sh:1.0.5
    networks:
      cadlab_net: {}
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    volumes:
    - ./certificates:/certificates:rw
    - ./configs:/etc/cadlab:rw
    - certs:/etc/ssl/cadlab:rw
    - acme:/root/.acme.sh:rw
    - ./logs/nginx:/var/log/nginx:delegated
    - source:/var/www:rw
version: '3.7'
volumes:
  acme: {}
  certs: {}
  data: {}
  source: {}

