networks:
  cadlab_net: {}
secrets:
  mysql_db_pass:
    external: true
    name: mysql_db_pass
  mysql_root_pass:
    external: true
    name: mysql_root_pass
services:
  cadlab:
    container_name: cadlab
    deploy:
      mode: global
    environment:
      CADLAB_INCLUDE_GIT: "true"
    image: docker.cadlab.io/cadlab
    networks:
      cadlab_net: {}
    secrets:
    - source: mysql_db_pass
    volumes:
    - ./configs:/etc/cadlab:rw
    - certs:/etc/ssl/cadlab:rw
    - ./backups:/var/backups:rw
    - git-backups:/var/git-backups:rw
    - git-configs:/var/git-configs:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - source:/var/www:rw
  git-server:
    container_name: git-server
    deploy:
      mode: global
    image: docker.cadlab.io/git-server
    networks:
      cadlab_net: {}
    volumes:
    - ./configs:/etc/cadlab:rw
    - git-configs:/etc/gitlab:rw
    - certs:/etc/ssl/cadlab:rw
    - git-data:/var/opt/gitlab:rw
    - git-backups:/var/opt/gitlab/backups:rw
  mail-server:
    container_name: mail-server
    deploy:
      mode: global
    image: docker.cadlab.io/mail-server
    networks:
      cadlab_net: {}
    volumes:
    - ./configs:/etc/cadlab:rw
  mysql:
    container_name: mysql
    deploy:
      mode: global
    environment:
      MYSQL_DATABASE: cadlab
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_db_pass
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
      MYSQL_USER: cadlab
    image: docker.cadlab.io/mysql
    networks:
      cadlab_net: {}
    secrets:
    - source: mysql_db_pass
    - source: mysql_root_pass
    volumes:
    - data:/var/lib/mysql:rw
  nginx:
    container_name: nginx
    deploy:
      mode: global
    environment:
      CADLAB_INCLUDE_GIT: "true"
    image: docker.cadlab.io/nginx
    networks:
      cadlab_net: {}
    ports:
    - 22:22/tcp
    - 80:80/tcp
    - 443:443/tcp
    volumes:
    - ./certificates:/certificates:rw
    - ./configs:/etc/cadlab:rw
    - certs:/etc/ssl/cadlab:rw
    - acme:/root/.acme.sh:rw
    - source:/var/www:rw
version: '3.7'
volumes:
  acme: {}
  certs: {}
  data: {}
  git-backups: {}
  git-configs: {}
  git-data: {}
  source: {}

