version: "3.7"
services:
  cadlab:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: docker.cadlab.io/cadlab-sh:1.18.22
    networks:
      cadlab_net: null
    secrets:
    - source: mysql_root_pass
    volumes:
    - type: bind
      source: ./configs
      target: /etc/cadlab
      bind:
        create_host_path: true
    - type: volume
      source: certs
      target: /etc/ssl/cadlab
      volume: {}
    - type: bind
      source: ./backups
      target: /var/cadlab/backups
      bind:
        create_host_path: true
    - type: bind
      source: ./logs/cadlab
      target: /var/log
      bind:
        create_host_path: true
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
    - type: volume
      source: source
      target: /var/www
      volume: {}
  mail-server:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: docker.cadlab.io/mail-server:1.0.3
    networks:
      cadlab_net: null
    volumes:
    - type: bind
      source: ./configs
      target: /etc/cadlab
      bind:
        create_host_path: true
  mysql:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      MYSQL_DATABASE: cadlab
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
    image: docker.cadlab.io/mysql-sh:1.0.17
    networks:
      cadlab_net: null
    secrets:
    - source: mysql_root_pass
    volumes:
    - type: volume
      source: data
      target: /var/lib/mysql
      volume: {}
    - type: bind
      source: ./logs/mysql
      target: /var/log/mysql
      bind:
        create_host_path: true
  nginx:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: docker.cadlab.io/nginx-sh:1.0.7
    networks:
      cadlab_net: null
    ports:
    - mode: host
      target: 80
      published: 80
      protocol: tcp
    - mode: host
      target: 443
      published: 443
      protocol: tcp
    volumes:
    - type: bind
      source: ./certificates
      target: /certificates
      bind:
        create_host_path: true
    - type: bind
      source: ./configs
      target: /etc/cadlab
      bind:
        create_host_path: true
    - type: volume
      source: certs
      target: /etc/ssl/cadlab
      volume: {}
    - type: volume
      source: acme
      target: /root/.acme.sh
      volume: {}
    - type: bind
      source: ./logs/nginx
      target: /var/log/nginx
      bind:
        create_host_path: true
    - type: volume
      source: source
      target: /var/www
      volume: {}
networks:
  cadlab_net:
    name: cadlab_cadlab_net
volumes:
  acme:
    name: cadlab_acme
  certs:
    name: cadlab_certs
  data:
    name: cadlab_data
  source:
    name: cadlab_source
secrets:
  mysql_root_pass:
    name: mysql_root_pass
    external: true
